const images = {
  logo: require('../images/logo.png'),
  img: require('../images/img.png'),
  text:require('../images/text.png'),
  video:require('../images/video.png'),
  hot:require('../images/hot.png'),
  top:require('../images/align-top.svg'),
  right:require('../images/align-right.svg'),
  bottom:require('../images/align-bottom.svg'),
  left:require('../images/align-left.svg'),
  alignCenter: require('../images/align-center.svg'),
  vCenter: require('../images/ver-center.svg'),
  open: require('../images/open.svg'),
  befor: require('../images/befor.svg'),
  after: require('../images/after.svg'),
  help: require('../images/help.svg'),
  call: require('../images/call.svg'),
  setattr: require('../images/set-attr.svg'),
  event: require('../images/event.svg'),
  animate: require('../images/animation.svg'),
  create: require('../images/creat.svg'),
  esc: require('../images/esc.svg'),
  save: require('../images/save.svg'),
  phone: require('../images/phone.png'),
  container:  require('../images/phone.png'),
  eyedisable:  require('../images/eye-disable.svg'),
  eye:  require('../images/eye.svg'),
  delet:  require('../images/delet.svg'),
  copy:  require('../images/copy.svg'),
  tabs:  require('../images/tabs.svg'),
  slider:  require('../images/slider.svg'),
  container:  require('../images/container.svg'),
  nav:  require('../images/nav.svg')
}

export default images
